### PR TITLE
Fix GPC tree

### PR DESCRIPTION
**Pull request by JoiRichi**
## Description of proposed changes

Use a manual alignment to fix the GPC reference numbering

## Related issue(s)

* https://github.com/nextstrain/lassa/issues/20
* https://github.com/nextstrain/lassa/issues/37
## Checklist

- [ ] Checks pass

### CODE REVIEW

**Comment by j23414** [comment]
I'll investigate the error, no action needed yet

**Comment by JoiRichi** [comment]
Alright. Thanks

**Comment by j23414** [comment]
For the sake of fixing the GPC alignment and investigating the error, I'm going to merge this and do subsequent hotfix.

**Comment by JoiRichi** [comment]
Great. I have the data for the other parts ready  btw :)

**Pull request merged**
