### PR TITLE
Update references to match RefSeq

### PR DESCRIPTION
**Pull request by j23414**
## Description of proposed changes

Switch to the [RefSeq reference 'Josiah'](https://www.ncbi.nlm.nih.gov/labs/virus/vssi/#/virus?SeqType_s=Nucleotide&VirusLineage_ss=Mammarenavirus%20lassaense,%20taxid:3052310&SourceDB_s=RefSeq) for consistency.

## Related issue(s)

* Addressing: https://github.com/nextstrain/lassa/issues/22

## Checklist

- [ ] Checks pass

### CODE REVIEW

**Comment by j23414** [comment]
Hmm, realizing that updating the references in phylogenetic triggers concurrent changes to segment references for ingest

* https://github.com/nextstrain/lassa/pull/12

**Comment by j23414** [comment]
I've moved the updating segment reference files to a separate issue. The main changes in this PR are from this [slack thread](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1723596521448139?thread_ts=1723584060.721629&cid=C01LCTT7JNN):

1. Add Pinneo as explicit root
2. Update reference to be Josiah

Which results in the following trees:

* https://next.nextstrain.org/staging/lassa/l/rooted
* https://next.nextstrain.org/staging/lassa/s/rooted

**Comment by trvrb** [comment]
Thanks for putting this together @j23414. In the above I just passed in two tips instead to specify a clade to root to. This isn't perfect, but is a bit less funky than TreeTime's behavior of placing root exactly on the specified tip.

Also, I added `include.txt` to make sure to always include these strains.

You can see resulting output here:
- https://nextstrain.org/staging/lassa/l/rooted-with-outgroup-clade
- https://nextstrain.org/staging/lassa/s/rooted-with-outgroup-clade

**Comment by trvrb** [comment]
@j23414: Could you add MG812675 to the example data? This should make the CI complete.

**Comment by j23414** [comment]
Thanks @trvrb! I was wondering how to get a more reasonable root of the trees

I've updated the example data in https://github.com/nextstrain/lassa/pull/23/commits/6405c92408284da61ab4be3d8183bc754e33221c

**Review by trvrb — APPROVED** [review]

**Pull request merged**
