### PR TITLE
Test if anyone sees this PR

### PR DESCRIPTION
**Pull request by j23414**
## Description of proposed changes

Not adding `core` as a reviewer, please add a comment if you see this PR

## Checklist

- [ ] Checks pass

### CODE REVIEW

**Comment by jameshadfield** [comment]
Github [differentiates](https://github.com/settings/notifications) between "Watching" and "Participating, @mentions and custom". For each category you can choose to get notifications via Email or GitHub. And you also have control over what repos you watch etc.

**Comment by tsibley** [comment]
Ditto what @jameshadfield said. I see the PR and his subsequent comment as two separate email notifications, sent to me because I'm watching (they're Cc'd to `<subscribed@noreply.github.com>`, which is [described](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#filtering-email-notifications) as "There was an update in a repository you're watching."). (Since my review wasn't requested via my user or a team I'm in, those emails go into my general PRs folder instead of a "someone asked you to look at something" folder.)

image

My [notification settings](https://github.com/settings/notifications) have me automatically watch repos and teams when I'm given access to them by default (but I can manually toggle individual repos/teams off later if I want).

image

So the notifications apply to newly created repos too.

**Comment by kimandrews** [comment]
I got email and github notifications about this PR too.

**Comment by genehack** [comment]
I got neither an email nor a notification, but I'm not watching the repo. 

I guess I will go watch every nextstrain repo now? 8^|

**Comment by victorlin** [comment]
I didn't receive an email/notification but will fix for future activity by watching the repo (and others under @nextstrain)

**Comment by j23414** [comment]
Thanks all! Yes, I was curious if not tagging `nextstrain/core` would affect the ability of potential reviewers to see PRs. I see we've settled on the following tagging protocol

> we have a mild lean against routinely tagging `core`; tagging `core` or specific people should be used only when you want specific special attention. In general, prefer tagging specific folks over core. Suggest making draft PR’s to indicate that you’re not ready for review.

**Pull request closed without merging**
